### ISSUE TITLE
Using the csv-parser to get all the values of a specific column

### ISSUE THREAD

**Issue by CleanHit** [vincentlaucsb/csv-parser#10]
Is there a way to iterate over the values of a specific column using a column name (string)? I've searched the documentation but didn't find a clear answer or an example to my question.

**Comment by vincentlaucsb** [comment]
Here's an example for printing the values of a specific column. I agree the documentation is a work in progress.

```
CSVReader reader("my_file.csv");

for (auto& row: reader) {
    std::cout << row["column_name"].get<>() << std::endl;
}
```

The documentation for the CSVRow object (auto& row) here (https://vincentlaucsb.github.io/csv-parser/classcsv_1_1CSVRow.html) describes the indexing and value retrieval methods.

**Comment by CleanHit** [comment]
Thanks for the fast reply, I actually saw that yesterday in the documentation and did try it like you wrote, but my IDE gave me some syntax error. Today it worked without any errors, maybe I just needed to restart my IDE....

This brings me to another question. Is this there a more package native way to iterate over each item of some column? Rather than using this:

```
vector<double_t> pickupLongitude;
for (csv::CSVRow &row: reader) {
    
    pickupLongitude.push_back(row["Pickup_longitude"].get<double_t>());
}

for (auto &item : pickupLongitude){
    
    cout.precision(20);
    cout << "Pickup longitude is: " << item << endl;
}
```

**Comment by vincentlaucsb** [comment]
The CSVReader was designed/optimized for reading values. If you want to modify the values, I would just have some custom logic populate another std::vector like you are doing right now.

However it is still possible to copy a `CSVRow` to a `std::vector<std::string>` by typing
```
std::vector<std::string>(row)
```
which you might find helpful.

The reason why you can't modify values is because CSVFields are just thin wrappers over string_views. Of course I could implement some feature to modify the original string, but that'd be very inefficient. Previous versions of the CSVReader spit out rows as `std::vector<std::string>`, but those implementations were 30% slower.

**Comment by CleanHit** [comment]
Thanks and good to know.
