### ISSUE TITLE
c++11 and c++ 14 support issues

### ISSUE THREAD

**Issue by xgdgsc** [vincentlaucsb/csv-parser#176]
Please checkout https://app.travis-ci.com/github/xgdgsc/csv-parser for errors regarding building using c++11 and c++14 with g++-9.

**Comment by vincentlaucsb** [comment]
Should be fixed by #177. I tested the latest release with g++7.5, g++ 8, and g++ 9.

**Comment by grunk** [comment]
Hello, thanks for this update.
I still have trouble withe followinf error : 

> Error (active)	E2783	expected a comma (the one-argument version of static_assert is not enabled in this mode)

Which refer to the use of static_assert. The static_assert declaration allows the message parameter to be omitted only since C++17
Ex : 
`static_assert(ParseFlags::DELIMITER < ParseFlags::NEWLINE);`
is invalid in C++11 and C++14
