### ISSUE TITLE
unable to correctly identify header row on simple csv file with comments

### ISSUE THREAD

**Issue by edgimar** [vincentlaucsb/csv-parser#67]
The library fails to correctly parse the header row of the simple CSV file contained in this archive: [test_data.zip](https://github.com/vincentlaucsb/csv-parser/files/3988782/test_data.zip)

The resulting column-names (from get_col_names()) are:
1. "# some extra metadata# some extra metadatatimestamp"
2. "distance"
3. "angle"
4. "amplitude"

Note how the first column-name includes the comment lines that precede the header line.

**Comment by vincentlaucsb** [comment]
Hi, thanks for reporting this issue. I'll take a look into it.

**Comment by edgimar** [comment]
Although not directly pertinent to this bug, one idea could be to make it possible to turn off comment autodetection, and instead allow one or more line prefixes to be specified that should be regarded as comments (no matter where they are found in the file).

**Comment by vincentlaucsb** [comment]
Thanks for the suggestion, but the cause turned out to be pretty simple (and stupid). Basically, when the parser skipped over a comment row, I forgot to tell it to move the "start of the current row" pointer. As a result, when the header row was finally read, leading comments got concatenated to the first column name.
